version: "3.8"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - dbdata6:/data/db


volumes:
  dbdata6:
